/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LegacyReferralInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "customerToReferrer"
      | "distributeNativeReward"
      | "distributeTokenReward"
      | "level1Bps"
      | "level2Bps"
      | "linkCustomer"
      | "operators"
      | "owner"
      | "referrers"
      | "registerReferrer"
      | "setOperator"
      | "setRewardSplits"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ParameterUpdated"
      | "ReferralLinked"
      | "ReferrerRegistered"
      | "RewardPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "customerToReferrer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeNativeReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeTokenReward",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "level1Bps", values?: undefined): string;
  encodeFunctionData(functionFragment: "level2Bps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "linkCustomer",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "referrers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerReferrer",
    values: [AddressLike, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardSplits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "customerToReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeNativeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeTokenReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "level1Bps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "level2Bps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "linkCustomer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "referrers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardSplits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ParameterUpdatedEvent {
  export type InputTuple = [
    parameterName: string,
    value: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    parameterName: string,
    value: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    parameterName: string;
    value: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralLinkedEvent {
  export type InputTuple = [
    customer: AddressLike,
    referrer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    customer: string,
    referrer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    customer: string;
    referrer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferrerRegisteredEvent {
  export type InputTuple = [
    referrer: AddressLike,
    namespaceHash: BytesLike,
    parentReferrer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    referrer: string,
    namespaceHash: string,
    parentReferrer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    referrer: string;
    namespaceHash: string;
    parentReferrer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardPaidEvent {
  export type InputTuple = [
    customer: AddressLike,
    referrer: AddressLike,
    amount: BigNumberish,
    tokenAddress: AddressLike,
    level: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    customer: string,
    referrer: string,
    amount: bigint,
    tokenAddress: string,
    level: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    customer: string;
    referrer: string;
    amount: bigint;
    tokenAddress: string;
    level: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegacyReferral extends BaseContract {
  connect(runner?: ContractRunner | null): LegacyReferral;
  waitForDeployment(): Promise<this>;

  interface: LegacyReferralInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  customerToReferrer: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  distributeNativeReward: TypedContractMethod<
    [customer: AddressLike],
    [void],
    "payable"
  >;

  distributeTokenReward: TypedContractMethod<
    [
      customer: AddressLike,
      tokenAddress: AddressLike,
      totalAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  level1Bps: TypedContractMethod<[], [bigint], "view">;

  level2Bps: TypedContractMethod<[], [bigint], "view">;

  linkCustomer: TypedContractMethod<
    [customer: AddressLike, referrer: AddressLike],
    [void],
    "nonpayable"
  >;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  referrers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        namespaceHash: string;
        parentReferrer: string;
        totalReferrals: bigint;
        totalEarned: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  registerReferrer: TypedContractMethod<
    [referrerAddr: AddressLike, namespace: string, parentReferrer: AddressLike],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [op: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setRewardSplits: TypedContractMethod<
    [_level1Bps: BigNumberish, _level2Bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "customerToReferrer"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "distributeNativeReward"
  ): TypedContractMethod<[customer: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "distributeTokenReward"
  ): TypedContractMethod<
    [
      customer: AddressLike,
      tokenAddress: AddressLike,
      totalAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "level1Bps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "level2Bps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "linkCustomer"
  ): TypedContractMethod<
    [customer: AddressLike, referrer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referrers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        namespaceHash: string;
        parentReferrer: string;
        totalReferrals: bigint;
        totalEarned: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerReferrer"
  ): TypedContractMethod<
    [referrerAddr: AddressLike, namespace: string, parentReferrer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [op: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRewardSplits"
  ): TypedContractMethod<
    [_level1Bps: BigNumberish, _level2Bps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ParameterUpdated"
  ): TypedContractEvent<
    ParameterUpdatedEvent.InputTuple,
    ParameterUpdatedEvent.OutputTuple,
    ParameterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralLinked"
  ): TypedContractEvent<
    ReferralLinkedEvent.InputTuple,
    ReferralLinkedEvent.OutputTuple,
    ReferralLinkedEvent.OutputObject
  >;
  getEvent(
    key: "ReferrerRegistered"
  ): TypedContractEvent<
    ReferrerRegisteredEvent.InputTuple,
    ReferrerRegisteredEvent.OutputTuple,
    ReferrerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RewardPaid"
  ): TypedContractEvent<
    RewardPaidEvent.InputTuple,
    RewardPaidEvent.OutputTuple,
    RewardPaidEvent.OutputObject
  >;

  filters: {
    "ParameterUpdated(string,uint256,uint256)": TypedContractEvent<
      ParameterUpdatedEvent.InputTuple,
      ParameterUpdatedEvent.OutputTuple,
      ParameterUpdatedEvent.OutputObject
    >;
    ParameterUpdated: TypedContractEvent<
      ParameterUpdatedEvent.InputTuple,
      ParameterUpdatedEvent.OutputTuple,
      ParameterUpdatedEvent.OutputObject
    >;

    "ReferralLinked(address,address,uint256)": TypedContractEvent<
      ReferralLinkedEvent.InputTuple,
      ReferralLinkedEvent.OutputTuple,
      ReferralLinkedEvent.OutputObject
    >;
    ReferralLinked: TypedContractEvent<
      ReferralLinkedEvent.InputTuple,
      ReferralLinkedEvent.OutputTuple,
      ReferralLinkedEvent.OutputObject
    >;

    "ReferrerRegistered(address,bytes32,address,uint256)": TypedContractEvent<
      ReferrerRegisteredEvent.InputTuple,
      ReferrerRegisteredEvent.OutputTuple,
      ReferrerRegisteredEvent.OutputObject
    >;
    ReferrerRegistered: TypedContractEvent<
      ReferrerRegisteredEvent.InputTuple,
      ReferrerRegisteredEvent.OutputTuple,
      ReferrerRegisteredEvent.OutputObject
    >;

    "RewardPaid(address,address,uint256,address,uint256,uint256)": TypedContractEvent<
      RewardPaidEvent.InputTuple,
      RewardPaidEvent.OutputTuple,
      RewardPaidEvent.OutputObject
    >;
    RewardPaid: TypedContractEvent<
      RewardPaidEvent.InputTuple,
      RewardPaidEvent.OutputTuple,
      RewardPaidEvent.OutputObject
    >;
  };
}
