/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "LegacyAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyAccessControl__factory>;
    getContractFactory(
      name: "LegacyAuditLog",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyAuditLog__factory>;
    getContractFactory(
      name: "LegacyNamespaceRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyNamespaceRegistry__factory>;
    getContractFactory(
      name: "LegacyPolicyEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyPolicyEngine__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "LegacyReferral",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyReferral__factory>;
    getContractFactory(
      name: "LegacyVaultAnchor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyVaultAnchor__factory>;
    getContractFactory(
      name: "LegacyVaultRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyVaultRegistry__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;

    getContractAt(
      name: "LegacyAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegacyAccessControl>;
    getContractAt(
      name: "LegacyAuditLog",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegacyAuditLog>;
    getContractAt(
      name: "LegacyNamespaceRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegacyNamespaceRegistry>;
    getContractAt(
      name: "LegacyPolicyEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegacyPolicyEngine>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "LegacyReferral",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegacyReferral>;
    getContractAt(
      name: "LegacyVaultAnchor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegacyVaultAnchor>;
    getContractAt(
      name: "LegacyVaultRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LegacyVaultRegistry>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;

    deployContract(
      name: "LegacyAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyAccessControl>;
    deployContract(
      name: "LegacyAuditLog",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyAuditLog>;
    deployContract(
      name: "LegacyNamespaceRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyNamespaceRegistry>;
    deployContract(
      name: "LegacyPolicyEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyPolicyEngine>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "LegacyReferral",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyReferral>;
    deployContract(
      name: "LegacyVaultAnchor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyVaultAnchor>;
    deployContract(
      name: "LegacyVaultRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyVaultRegistry>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;

    deployContract(
      name: "LegacyAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyAccessControl>;
    deployContract(
      name: "LegacyAuditLog",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyAuditLog>;
    deployContract(
      name: "LegacyNamespaceRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyNamespaceRegistry>;
    deployContract(
      name: "LegacyPolicyEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyPolicyEngine>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "LegacyReferral",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyReferral>;
    deployContract(
      name: "LegacyVaultAnchor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyVaultAnchor>;
    deployContract(
      name: "LegacyVaultRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LegacyVaultRegistry>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
