/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as legacyReferralSol from "./LegacyReferral.sol";
export type { legacyReferralSol };
export type { LegacyAccessControl } from "./LegacyAccessControl";
export type { LegacyAuditLog } from "./LegacyAuditLog";
export type { LegacyNamespaceRegistry } from "./LegacyNamespaceRegistry";
export type { LegacyPolicyEngine } from "./LegacyPolicyEngine";
export type { LegacyVaultAnchor } from "./LegacyVaultAnchor";
export type { LegacyVaultRegistry } from "./LegacyVaultRegistry";
export type { MockERC20 } from "./MockERC20";
export * as factories from "./factories";
export { LegacyAccessControl__factory } from "./factories/LegacyAccessControl__factory";
export { LegacyAuditLog__factory } from "./factories/LegacyAuditLog__factory";
export { LegacyNamespaceRegistry__factory } from "./factories/LegacyNamespaceRegistry__factory";
export { LegacyPolicyEngine__factory } from "./factories/LegacyPolicyEngine__factory";
export type { IERC20 } from "./LegacyReferral.sol/IERC20";
export { IERC20__factory } from "./factories/LegacyReferral.sol/IERC20__factory";
export type { LegacyReferral } from "./LegacyReferral.sol/LegacyReferral";
export { LegacyReferral__factory } from "./factories/LegacyReferral.sol/LegacyReferral__factory";
export { LegacyVaultAnchor__factory } from "./factories/LegacyVaultAnchor__factory";
export { LegacyVaultRegistry__factory } from "./factories/LegacyVaultRegistry__factory";
export { MockERC20__factory } from "./factories/MockERC20__factory";
