/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LegacyAccessControl {
  export type AccessGrantStruct = {
    id: BigNumberish;
    vaultId: string;
    granteeId: string;
    granteeDID: string;
    scope: BigNumberish;
    itemsHash: BytesLike;
    grantedBy: AddressLike;
    grantedAt: BigNumberish;
    expiresAt: BigNumberish;
    revoked: boolean;
    revokedAt: BigNumberish;
  };

  export type AccessGrantStructOutput = [
    id: bigint,
    vaultId: string,
    granteeId: string,
    granteeDID: string,
    scope: bigint,
    itemsHash: string,
    grantedBy: string,
    grantedAt: bigint,
    expiresAt: bigint,
    revoked: boolean,
    revokedAt: bigint
  ] & {
    id: bigint;
    vaultId: string;
    granteeId: string;
    granteeDID: string;
    scope: bigint;
    itemsHash: string;
    grantedBy: string;
    grantedAt: bigint;
    expiresAt: bigint;
    revoked: boolean;
    revokedAt: bigint;
  };
}

export interface LegacyAccessControlInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOperator"
      | "getGrant"
      | "getGranteeGrants"
      | "getVaultGrants"
      | "hasActiveGrant"
      | "issueGrant"
      | "operators"
      | "owner"
      | "removeOperator"
      | "revokeGrant"
      | "totalGrants"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AccessGranted" | "AccessRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGrant",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGranteeGrants",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultGrants",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveGrant",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "issueGrant",
    values: [string, string, string, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeGrant",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalGrants",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGrant", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGranteeGrants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultGrants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issueGrant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalGrants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    id: BigNumberish,
    vaultId: string,
    granteeId: string,
    granteeDID: string,
    scope: BigNumberish,
    grantedAt: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    vaultId: string,
    granteeId: string,
    granteeDID: string,
    scope: bigint,
    grantedAt: bigint
  ];
  export interface OutputObject {
    id: bigint;
    vaultId: string;
    granteeId: string;
    granteeDID: string;
    scope: bigint;
    grantedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [
    id: BigNumberish,
    vaultId: string,
    granteeId: string,
    revokedBy: AddressLike,
    revokedAt: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    vaultId: string,
    granteeId: string,
    revokedBy: string,
    revokedAt: bigint
  ];
  export interface OutputObject {
    id: bigint;
    vaultId: string;
    granteeId: string;
    revokedBy: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegacyAccessControl extends BaseContract {
  connect(runner?: ContractRunner | null): LegacyAccessControl;
  waitForDeployment(): Promise<this>;

  interface: LegacyAccessControlInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  getGrant: TypedContractMethod<
    [grantId: BigNumberish],
    [LegacyAccessControl.AccessGrantStructOutput],
    "view"
  >;

  getGranteeGrants: TypedContractMethod<
    [granteeId: string],
    [bigint[]],
    "view"
  >;

  getVaultGrants: TypedContractMethod<[vaultId: string], [bigint[]], "view">;

  hasActiveGrant: TypedContractMethod<
    [vaultId: string, granteeId: string],
    [[boolean, bigint]],
    "view"
  >;

  issueGrant: TypedContractMethod<
    [
      vaultId: string,
      granteeId: string,
      granteeDID: string,
      scope: BigNumberish,
      itemsHash: BytesLike,
      expiresAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  revokeGrant: TypedContractMethod<
    [grantId: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalGrants: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getGrant"
  ): TypedContractMethod<
    [grantId: BigNumberish],
    [LegacyAccessControl.AccessGrantStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGranteeGrants"
  ): TypedContractMethod<[granteeId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVaultGrants"
  ): TypedContractMethod<[vaultId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasActiveGrant"
  ): TypedContractMethod<
    [vaultId: string, granteeId: string],
    [[boolean, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueGrant"
  ): TypedContractMethod<
    [
      vaultId: string,
      granteeId: string,
      granteeDID: string,
      scope: BigNumberish,
      itemsHash: BytesLike,
      expiresAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeGrant"
  ): TypedContractMethod<[grantId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalGrants"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(uint256,string,string,string,uint8,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRevoked(uint256,string,string,address,uint256)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
  };
}
