/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LegacyVaultRegistry {
  export type VaultRecordStruct = {
    vaultId: string;
    ownerDID: string;
    encryptedManifestCID: string;
    manifestHash: BytesLike;
    releasePolicyId: string;
    status: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
    exists: boolean;
  };

  export type VaultRecordStructOutput = [
    vaultId: string,
    ownerDID: string,
    encryptedManifestCID: string,
    manifestHash: string,
    releasePolicyId: string,
    status: bigint,
    createdAt: bigint,
    updatedAt: bigint,
    exists: boolean
  ] & {
    vaultId: string;
    ownerDID: string;
    encryptedManifestCID: string;
    manifestHash: string;
    releasePolicyId: string;
    status: bigint;
    createdAt: bigint;
    updatedAt: bigint;
    exists: boolean;
  };

  export type ChainEventStruct = {
    eventName: string;
    vaultId: string;
    dataHash: BytesLike;
    blockHeight: BigNumberish;
    timestamp: BigNumberish;
  };

  export type ChainEventStructOutput = [
    eventName: string,
    vaultId: string,
    dataHash: string,
    blockHeight: bigint,
    timestamp: bigint
  ] & {
    eventName: string;
    vaultId: string;
    dataHash: string;
    blockHeight: bigint;
    timestamp: bigint;
  };
}

export interface LegacyVaultRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOperator"
      | "anchorAuditEvent"
      | "auditLog"
      | "getVault"
      | "getVaultEvents"
      | "getVaultStatus"
      | "operators"
      | "owner"
      | "policyEngine"
      | "registerVault"
      | "removeOperator"
      | "setAuditLog"
      | "setPolicyEngine"
      | "setVaultStatus"
      | "transferOwnership"
      | "updateManifest"
      | "vaultRegistered"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditEventAnchored"
      | "ManifestUpdated"
      | "OperatorAdded"
      | "OperatorRemoved"
      | "VaultCreated"
      | "VaultStatusChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorAuditEvent",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "auditLog", values?: undefined): string;
  encodeFunctionData(functionFragment: "getVault", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getVaultEvents",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policyEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerVault",
    values: [string, string, string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuditLog",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicyEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultStatus",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateManifest",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultRegistered",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorAuditEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auditLog", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuditLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPolicyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVaultStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateManifest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultRegistered",
    data: BytesLike
  ): Result;
}

export namespace AuditEventAnchoredEvent {
  export type InputTuple = [
    vaultId: string,
    eventId: string,
    eventHash: BytesLike,
    blockHeight: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    eventId: string,
    eventHash: string,
    blockHeight: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    eventId: string;
    eventHash: string;
    blockHeight: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManifestUpdatedEvent {
  export type InputTuple = [
    vaultId: string,
    newCID: string,
    newHash: BytesLike,
    version: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    newCID: string,
    newHash: string,
    version: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    newCID: string;
    newHash: string;
    version: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorAddedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorRemovedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    vaultId: string,
    ownerDID: string,
    manifestCID: string,
    manifestHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    ownerDID: string,
    manifestCID: string,
    manifestHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    ownerDID: string;
    manifestCID: string;
    manifestHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultStatusChangedEvent {
  export type InputTuple = [
    vaultId: string,
    previousStatus: BigNumberish,
    newStatus: BigNumberish,
    changedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    previousStatus: bigint,
    newStatus: bigint,
    changedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    previousStatus: bigint;
    newStatus: bigint;
    changedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegacyVaultRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LegacyVaultRegistry;
  waitForDeployment(): Promise<this>;

  interface: LegacyVaultRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  anchorAuditEvent: TypedContractMethod<
    [vaultId: string, eventId: string, eventHash: BytesLike],
    [void],
    "nonpayable"
  >;

  auditLog: TypedContractMethod<[], [string], "view">;

  getVault: TypedContractMethod<
    [vaultId: string],
    [LegacyVaultRegistry.VaultRecordStructOutput],
    "view"
  >;

  getVaultEvents: TypedContractMethod<
    [vaultId: string],
    [LegacyVaultRegistry.ChainEventStructOutput[]],
    "view"
  >;

  getVaultStatus: TypedContractMethod<[vaultId: string], [bigint], "view">;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policyEngine: TypedContractMethod<[], [string], "view">;

  registerVault: TypedContractMethod<
    [
      vaultId: string,
      ownerDID: string,
      manifestCID: string,
      manifestHash: BytesLike,
      releasePolicyId: string
    ],
    [void],
    "nonpayable"
  >;

  removeOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  setAuditLog: TypedContractMethod<[_al: AddressLike], [void], "nonpayable">;

  setPolicyEngine: TypedContractMethod<
    [_pe: AddressLike],
    [void],
    "nonpayable"
  >;

  setVaultStatus: TypedContractMethod<
    [vaultId: string, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateManifest: TypedContractMethod<
    [vaultId: string, newCID: string, newHash: BytesLike],
    [void],
    "nonpayable"
  >;

  vaultRegistered: TypedContractMethod<[vaultId: string], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "anchorAuditEvent"
  ): TypedContractMethod<
    [vaultId: string, eventId: string, eventHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "auditLog"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getVault"
  ): TypedContractMethod<
    [vaultId: string],
    [LegacyVaultRegistry.VaultRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultEvents"
  ): TypedContractMethod<
    [vaultId: string],
    [LegacyVaultRegistry.ChainEventStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultStatus"
  ): TypedContractMethod<[vaultId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policyEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerVault"
  ): TypedContractMethod<
    [
      vaultId: string,
      ownerDID: string,
      manifestCID: string,
      manifestHash: BytesLike,
      releasePolicyId: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuditLog"
  ): TypedContractMethod<[_al: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPolicyEngine"
  ): TypedContractMethod<[_pe: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVaultStatus"
  ): TypedContractMethod<
    [vaultId: string, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateManifest"
  ): TypedContractMethod<
    [vaultId: string, newCID: string, newHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaultRegistered"
  ): TypedContractMethod<[vaultId: string], [boolean], "view">;

  getEvent(
    key: "AuditEventAnchored"
  ): TypedContractEvent<
    AuditEventAnchoredEvent.InputTuple,
    AuditEventAnchoredEvent.OutputTuple,
    AuditEventAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "ManifestUpdated"
  ): TypedContractEvent<
    ManifestUpdatedEvent.InputTuple,
    ManifestUpdatedEvent.OutputTuple,
    ManifestUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorAdded"
  ): TypedContractEvent<
    OperatorAddedEvent.InputTuple,
    OperatorAddedEvent.OutputTuple,
    OperatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorRemoved"
  ): TypedContractEvent<
    OperatorRemovedEvent.InputTuple,
    OperatorRemovedEvent.OutputTuple,
    OperatorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultStatusChanged"
  ): TypedContractEvent<
    VaultStatusChangedEvent.InputTuple,
    VaultStatusChangedEvent.OutputTuple,
    VaultStatusChangedEvent.OutputObject
  >;

  filters: {
    "AuditEventAnchored(string,string,bytes32,uint256,uint256)": TypedContractEvent<
      AuditEventAnchoredEvent.InputTuple,
      AuditEventAnchoredEvent.OutputTuple,
      AuditEventAnchoredEvent.OutputObject
    >;
    AuditEventAnchored: TypedContractEvent<
      AuditEventAnchoredEvent.InputTuple,
      AuditEventAnchoredEvent.OutputTuple,
      AuditEventAnchoredEvent.OutputObject
    >;

    "ManifestUpdated(string,string,bytes32,uint256,uint256)": TypedContractEvent<
      ManifestUpdatedEvent.InputTuple,
      ManifestUpdatedEvent.OutputTuple,
      ManifestUpdatedEvent.OutputObject
    >;
    ManifestUpdated: TypedContractEvent<
      ManifestUpdatedEvent.InputTuple,
      ManifestUpdatedEvent.OutputTuple,
      ManifestUpdatedEvent.OutputObject
    >;

    "OperatorAdded(address)": TypedContractEvent<
      OperatorAddedEvent.InputTuple,
      OperatorAddedEvent.OutputTuple,
      OperatorAddedEvent.OutputObject
    >;
    OperatorAdded: TypedContractEvent<
      OperatorAddedEvent.InputTuple,
      OperatorAddedEvent.OutputTuple,
      OperatorAddedEvent.OutputObject
    >;

    "OperatorRemoved(address)": TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;
    OperatorRemoved: TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;

    "VaultCreated(string,string,string,bytes32,uint256)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;

    "VaultStatusChanged(string,uint8,uint8,address,uint256)": TypedContractEvent<
      VaultStatusChangedEvent.InputTuple,
      VaultStatusChangedEvent.OutputTuple,
      VaultStatusChangedEvent.OutputObject
    >;
    VaultStatusChanged: TypedContractEvent<
      VaultStatusChangedEvent.InputTuple,
      VaultStatusChangedEvent.OutputTuple,
      VaultStatusChangedEvent.OutputObject
    >;
  };
}
