/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LegacyAuditLog {
  export type AuditEventStruct = {
    id: BigNumberish;
    vaultId: string;
    actorId: string;
    action: BigNumberish;
    targetHash: BytesLike;
    metadataHash: BytesLike;
    previousHash: BytesLike;
    timestamp: BigNumberish;
    blockHeight: BigNumberish;
  };

  export type AuditEventStructOutput = [
    id: bigint,
    vaultId: string,
    actorId: string,
    action: bigint,
    targetHash: string,
    metadataHash: string,
    previousHash: string,
    timestamp: bigint,
    blockHeight: bigint
  ] & {
    id: bigint;
    vaultId: string;
    actorId: string;
    action: bigint;
    targetHash: string;
    metadataHash: string;
    previousHash: string;
    timestamp: bigint;
    blockHeight: bigint;
  };
}

export interface LegacyAuditLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOperator"
      | "getEvent"
      | "getLatestEvents"
      | "getVaultEventIds"
      | "latestHash"
      | "operators"
      | "owner"
      | "recordEvent"
      | "removeOperator"
      | "totalEvents"
      | "transferOwnership"
      | "verifyChain"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AuditEventRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestEvents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultEventIds",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "latestHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordEvent",
    values: [string, string, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalEvents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyChain",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLatestEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultEventIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "latestHash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyChain",
    data: BytesLike
  ): Result;
}

export namespace AuditEventRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    vaultId: string,
    action: BigNumberish,
    eventHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    vaultId: string,
    action: bigint,
    eventHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    vaultId: string;
    action: bigint;
    eventHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegacyAuditLog extends BaseContract {
  connect(runner?: ContractRunner | null): LegacyAuditLog;
  waitForDeployment(): Promise<this>;

  interface: LegacyAuditLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  getEvent: TypedContractMethod<
    [eventId: BigNumberish],
    [LegacyAuditLog.AuditEventStructOutput],
    "view"
  >;

  getLatestEvents: TypedContractMethod<
    [count: BigNumberish],
    [LegacyAuditLog.AuditEventStructOutput[]],
    "view"
  >;

  getVaultEventIds: TypedContractMethod<[vaultId: string], [bigint[]], "view">;

  latestHash: TypedContractMethod<[], [string], "view">;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordEvent: TypedContractMethod<
    [
      vaultId: string,
      actorId: string,
      action: BigNumberish,
      targetHash: BytesLike,
      metadataHash: BytesLike
    ],
    [[bigint, string] & { eventId: bigint; eventHash: string }],
    "nonpayable"
  >;

  removeOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  totalEvents: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyChain: TypedContractMethod<
    [fromId: BigNumberish, toId: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEvent"
  ): TypedContractMethod<
    [eventId: BigNumberish],
    [LegacyAuditLog.AuditEventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestEvents"
  ): TypedContractMethod<
    [count: BigNumberish],
    [LegacyAuditLog.AuditEventStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultEventIds"
  ): TypedContractMethod<[vaultId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "latestHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordEvent"
  ): TypedContractMethod<
    [
      vaultId: string,
      actorId: string,
      action: BigNumberish,
      targetHash: BytesLike,
      metadataHash: BytesLike
    ],
    [[bigint, string] & { eventId: bigint; eventHash: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalEvents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyChain"
  ): TypedContractMethod<
    [fromId: BigNumberish, toId: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AuditEventRecorded"
  ): TypedContractEvent<
    AuditEventRecordedEvent.InputTuple,
    AuditEventRecordedEvent.OutputTuple,
    AuditEventRecordedEvent.OutputObject
  >;

  filters: {
    "AuditEventRecorded(uint256,string,uint8,bytes32,uint256)": TypedContractEvent<
      AuditEventRecordedEvent.InputTuple,
      AuditEventRecordedEvent.OutputTuple,
      AuditEventRecordedEvent.OutputObject
    >;
    AuditEventRecorded: TypedContractEvent<
      AuditEventRecordedEvent.InputTuple,
      AuditEventRecordedEvent.OutputTuple,
      AuditEventRecordedEvent.OutputObject
    >;
  };
}
