/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LegacyNamespaceRegistry {
  export type MemberStruct = {
    account: AddressLike;
    did: string;
    role: BigNumberish;
    addedAt: BigNumberish;
    active: boolean;
  };

  export type MemberStructOutput = [
    account: string,
    did: string,
    role: bigint,
    addedAt: bigint,
    active: boolean
  ] & {
    account: string;
    did: string;
    role: bigint;
    addedAt: bigint;
    active: boolean;
  };

  export type NamespaceRecordStruct = {
    labelHash: BytesLike;
    label: string;
    ownerAddr: AddressLike;
    ownerDID: string;
    status: BigNumberish;
    planTier: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
    exists: boolean;
  };

  export type NamespaceRecordStructOutput = [
    labelHash: string,
    label: string,
    ownerAddr: string,
    ownerDID: string,
    status: bigint,
    planTier: bigint,
    createdAt: bigint,
    updatedAt: bigint,
    exists: boolean
  ] & {
    labelHash: string;
    label: string;
    ownerAddr: string;
    ownerDID: string;
    status: bigint;
    planTier: bigint;
    createdAt: bigint;
    updatedAt: bigint;
    exists: boolean;
  };
}

export interface LegacyNamespaceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMember"
      | "addOperator"
      | "getMembers"
      | "getNamespace"
      | "getOwnerNamespaces"
      | "namespaceExists"
      | "operators"
      | "owner"
      | "registerNamespace"
      | "removeMember"
      | "removeOperator"
      | "setNamespaceStatus"
      | "transferNamespaceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MemberAdded"
      | "MemberRemoved"
      | "NamespaceRegistered"
      | "NamespaceStatusChanged"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMember",
    values: [string, AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getMembers", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getNamespace",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerNamespaces",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "namespaceExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerNamespace",
    values: [string, AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNamespaceStatus",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferNamespaceOwnership",
    values: [string, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMembers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNamespace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerNamespaces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "namespaceExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerNamespace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNamespaceStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferNamespaceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MemberAddedEvent {
  export type InputTuple = [
    labelHash: BytesLike,
    account: AddressLike,
    did: string,
    role: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    labelHash: string,
    account: string,
    did: string,
    role: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    labelHash: string;
    account: string;
    did: string;
    role: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRemovedEvent {
  export type InputTuple = [
    labelHash: BytesLike,
    account: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    labelHash: string,
    account: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    labelHash: string;
    account: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NamespaceRegisteredEvent {
  export type InputTuple = [
    labelHash: BytesLike,
    label: string,
    ownerAddr: AddressLike,
    ownerDID: string,
    planTier: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    labelHash: string,
    label: string,
    ownerAddr: string,
    ownerDID: string,
    planTier: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    labelHash: string;
    label: string;
    ownerAddr: string;
    ownerDID: string;
    planTier: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NamespaceStatusChangedEvent {
  export type InputTuple = [
    labelHash: BytesLike,
    previousStatus: BigNumberish,
    newStatus: BigNumberish,
    changedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    labelHash: string,
    previousStatus: bigint,
    newStatus: bigint,
    changedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    labelHash: string;
    previousStatus: bigint;
    newStatus: bigint;
    changedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    labelHash: BytesLike,
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    labelHash: string,
    from: string,
    to: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    labelHash: string;
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegacyNamespaceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LegacyNamespaceRegistry;
  waitForDeployment(): Promise<this>;

  interface: LegacyNamespaceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMember: TypedContractMethod<
    [
      label: string,
      memberAddr: AddressLike,
      memberDID: string,
      role: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  getMembers: TypedContractMethod<
    [label: string],
    [LegacyNamespaceRegistry.MemberStructOutput[]],
    "view"
  >;

  getNamespace: TypedContractMethod<
    [label: string],
    [LegacyNamespaceRegistry.NamespaceRecordStructOutput],
    "view"
  >;

  getOwnerNamespaces: TypedContractMethod<
    [ownerAddr: AddressLike],
    [string[]],
    "view"
  >;

  namespaceExists: TypedContractMethod<[label: string], [boolean], "view">;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerNamespace: TypedContractMethod<
    [
      label: string,
      ownerAddr: AddressLike,
      ownerDID: string,
      planTier: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  removeMember: TypedContractMethod<
    [label: string, memberAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  removeOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  setNamespaceStatus: TypedContractMethod<
    [label: string, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferNamespaceOwnership: TypedContractMethod<
    [label: string, newOwner: AddressLike, newOwnerDID: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMember"
  ): TypedContractMethod<
    [
      label: string,
      memberAddr: AddressLike,
      memberDID: string,
      role: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMembers"
  ): TypedContractMethod<
    [label: string],
    [LegacyNamespaceRegistry.MemberStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNamespace"
  ): TypedContractMethod<
    [label: string],
    [LegacyNamespaceRegistry.NamespaceRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerNamespaces"
  ): TypedContractMethod<[ownerAddr: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "namespaceExists"
  ): TypedContractMethod<[label: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerNamespace"
  ): TypedContractMethod<
    [
      label: string,
      ownerAddr: AddressLike,
      ownerDID: string,
      planTier: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeMember"
  ): TypedContractMethod<
    [label: string, memberAddr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNamespaceStatus"
  ): TypedContractMethod<
    [label: string, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferNamespaceOwnership"
  ): TypedContractMethod<
    [label: string, newOwner: AddressLike, newOwnerDID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MemberAdded"
  ): TypedContractEvent<
    MemberAddedEvent.InputTuple,
    MemberAddedEvent.OutputTuple,
    MemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRemoved"
  ): TypedContractEvent<
    MemberRemovedEvent.InputTuple,
    MemberRemovedEvent.OutputTuple,
    MemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "NamespaceRegistered"
  ): TypedContractEvent<
    NamespaceRegisteredEvent.InputTuple,
    NamespaceRegisteredEvent.OutputTuple,
    NamespaceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "NamespaceStatusChanged"
  ): TypedContractEvent<
    NamespaceStatusChangedEvent.InputTuple,
    NamespaceStatusChangedEvent.OutputTuple,
    NamespaceStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "MemberAdded(bytes32,address,string,uint8,uint256)": TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;
    MemberAdded: TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;

    "MemberRemoved(bytes32,address,uint256)": TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;
    MemberRemoved: TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;

    "NamespaceRegistered(bytes32,string,address,string,uint256,uint256)": TypedContractEvent<
      NamespaceRegisteredEvent.InputTuple,
      NamespaceRegisteredEvent.OutputTuple,
      NamespaceRegisteredEvent.OutputObject
    >;
    NamespaceRegistered: TypedContractEvent<
      NamespaceRegisteredEvent.InputTuple,
      NamespaceRegisteredEvent.OutputTuple,
      NamespaceRegisteredEvent.OutputObject
    >;

    "NamespaceStatusChanged(bytes32,uint8,uint8,address,uint256)": TypedContractEvent<
      NamespaceStatusChangedEvent.InputTuple,
      NamespaceStatusChangedEvent.OutputTuple,
      NamespaceStatusChangedEvent.OutputObject
    >;
    NamespaceStatusChanged: TypedContractEvent<
      NamespaceStatusChangedEvent.InputTuple,
      NamespaceStatusChangedEvent.OutputTuple,
      NamespaceStatusChangedEvent.OutputObject
    >;

    "OwnershipTransferred(bytes32,address,address,uint256)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
