/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LegacyPolicyEngine {
  export type ReleaseStateStruct = {
    vaultId: string;
    claimId: string;
    identityVerified: boolean;
    deathCertUploaded: boolean;
    attorneyAttested: boolean;
    guardianApprovals: BigNumberish;
    guardianQuorumMet: boolean;
    quorumMetAt: BigNumberish;
    waitingPeriodComplete: boolean;
    waitingPeriodEndsAt: BigNumberish;
    disputed: boolean;
    released: boolean;
    denied: boolean;
    exists: boolean;
  };

  export type ReleaseStateStructOutput = [
    vaultId: string,
    claimId: string,
    identityVerified: boolean,
    deathCertUploaded: boolean,
    attorneyAttested: boolean,
    guardianApprovals: bigint,
    guardianQuorumMet: boolean,
    quorumMetAt: bigint,
    waitingPeriodComplete: boolean,
    waitingPeriodEndsAt: bigint,
    disputed: boolean,
    released: boolean,
    denied: boolean,
    exists: boolean
  ] & {
    vaultId: string;
    claimId: string;
    identityVerified: boolean;
    deathCertUploaded: boolean;
    attorneyAttested: boolean;
    guardianApprovals: bigint;
    guardianQuorumMet: boolean;
    quorumMetAt: bigint;
    waitingPeriodComplete: boolean;
    waitingPeriodEndsAt: bigint;
    disputed: boolean;
    released: boolean;
    denied: boolean;
    exists: boolean;
  };

  export type ConditionRecordStruct = {
    condition: BigNumberish;
    satisfiedBy: AddressLike;
    evidenceHash: BytesLike;
    satisfiedAt: BigNumberish;
  };

  export type ConditionRecordStructOutput = [
    condition: bigint,
    satisfiedBy: string,
    evidenceHash: string,
    satisfiedAt: bigint
  ] & {
    condition: bigint;
    satisfiedBy: string;
    evidenceHash: string;
    satisfiedAt: bigint;
  };

  export type ReleasePolicyStruct = {
    vaultId: string;
    policyId: string;
    requireExecutorIdentity: boolean;
    requireDeathCertificate: boolean;
    requireAttorneyAttestation: boolean;
    requireGuardianQuorum: boolean;
    guardianQuorumN: BigNumberish;
    guardianQuorumM: BigNumberish;
    waitingPeriodDays: BigNumberish;
    policyHash: BigNumberish;
    anchoredAt: BigNumberish;
    version: BigNumberish;
    exists: boolean;
  };

  export type ReleasePolicyStructOutput = [
    vaultId: string,
    policyId: string,
    requireExecutorIdentity: boolean,
    requireDeathCertificate: boolean,
    requireAttorneyAttestation: boolean,
    requireGuardianQuorum: boolean,
    guardianQuorumN: bigint,
    guardianQuorumM: bigint,
    waitingPeriodDays: bigint,
    policyHash: bigint,
    anchoredAt: bigint,
    version: bigint,
    exists: boolean
  ] & {
    vaultId: string;
    policyId: string;
    requireExecutorIdentity: boolean;
    requireDeathCertificate: boolean;
    requireAttorneyAttestation: boolean;
    requireGuardianQuorum: boolean;
    guardianQuorumN: bigint;
    guardianQuorumM: bigint;
    waitingPeriodDays: bigint;
    policyHash: bigint;
    anchoredAt: bigint;
    version: bigint;
    exists: boolean;
  };
}

export interface LegacyPolicyEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOperator"
      | "allConditionsMet"
      | "anchorPolicy"
      | "authoriseRelease"
      | "denyClaim"
      | "getClaimState"
      | "getConditions"
      | "getPolicy"
      | "openClaim"
      | "operators"
      | "owner"
      | "raiseDispute"
      | "removeOperator"
      | "resolveDispute"
      | "satisfyCondition"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimDenied"
      | "ClaimOpened"
      | "ConditionSatisfied"
      | "DisputeRaised"
      | "DisputeResolved"
      | "PolicyAnchored"
      | "ReleaseAuthorised"
      | "WaitingPeriodStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allConditionsMet",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorPolicy",
    values: [
      string,
      string,
      boolean,
      boolean,
      boolean,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "authoriseRelease",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "denyClaim",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimState",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getConditions",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getPolicy", values: [string]): string;
  encodeFunctionData(
    functionFragment: "openClaim",
    values: [string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "satisfyCondition",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allConditionsMet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authoriseRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "denyClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "openClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "satisfyCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ClaimDeniedEvent {
  export type InputTuple = [
    claimId: string,
    reason: string,
    deniedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    claimId: string,
    reason: string,
    deniedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    claimId: string;
    reason: string;
    deniedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimOpenedEvent {
  export type InputTuple = [
    vaultId: string,
    claimId: string,
    claimant: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    claimId: string,
    claimant: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    claimId: string;
    claimant: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionSatisfiedEvent {
  export type InputTuple = [
    claimId: string,
    condition: BigNumberish,
    satisfiedBy: AddressLike,
    evidenceHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    claimId: string,
    condition: bigint,
    satisfiedBy: string,
    evidenceHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    claimId: string;
    condition: bigint;
    satisfiedBy: string;
    evidenceHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [
    claimId: string,
    reason: string,
    raisedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    claimId: string,
    reason: string,
    raisedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    claimId: string;
    reason: string;
    raisedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    claimId: string,
    releaseProceeds: boolean,
    resolvedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    claimId: string,
    releaseProceeds: boolean,
    resolvedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    claimId: string;
    releaseProceeds: boolean;
    resolvedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyAnchoredEvent {
  export type InputTuple = [
    vaultId: string,
    policyId: string,
    policyHash: BigNumberish,
    version: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    policyId: string,
    policyHash: bigint,
    version: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    policyId: string;
    policyHash: bigint;
    version: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseAuthorisedEvent {
  export type InputTuple = [
    vaultId: string,
    claimId: string,
    conditionsHash: BytesLike,
    authorisedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    claimId: string,
    conditionsHash: string,
    authorisedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    claimId: string;
    conditionsHash: string;
    authorisedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WaitingPeriodStartedEvent {
  export type InputTuple = [claimId: string, endsAt: BigNumberish];
  export type OutputTuple = [claimId: string, endsAt: bigint];
  export interface OutputObject {
    claimId: string;
    endsAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegacyPolicyEngine extends BaseContract {
  connect(runner?: ContractRunner | null): LegacyPolicyEngine;
  waitForDeployment(): Promise<this>;

  interface: LegacyPolicyEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  allConditionsMet: TypedContractMethod<[claimId: string], [boolean], "view">;

  anchorPolicy: TypedContractMethod<
    [
      vaultId: string,
      policyId: string,
      requireExecutorIdentity: boolean,
      requireDeathCertificate: boolean,
      requireAttorneyAttestation: boolean,
      requireGuardianQuorum: boolean,
      guardianQuorumN: BigNumberish,
      guardianQuorumM: BigNumberish,
      waitingPeriodDays: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  authoriseRelease: TypedContractMethod<
    [vaultId: string, claimId: string],
    [string],
    "nonpayable"
  >;

  denyClaim: TypedContractMethod<
    [claimId: string, reason: string],
    [void],
    "nonpayable"
  >;

  getClaimState: TypedContractMethod<
    [claimId: string],
    [LegacyPolicyEngine.ReleaseStateStructOutput],
    "view"
  >;

  getConditions: TypedContractMethod<
    [claimId: string],
    [LegacyPolicyEngine.ConditionRecordStructOutput[]],
    "view"
  >;

  getPolicy: TypedContractMethod<
    [vaultId: string],
    [LegacyPolicyEngine.ReleasePolicyStructOutput],
    "view"
  >;

  openClaim: TypedContractMethod<
    [vaultId: string, claimId: string, claimant: AddressLike],
    [void],
    "nonpayable"
  >;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  raiseDispute: TypedContractMethod<
    [claimId: string, reason: string],
    [void],
    "nonpayable"
  >;

  removeOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [claimId: string, releaseProceeds: boolean],
    [void],
    "nonpayable"
  >;

  satisfyCondition: TypedContractMethod<
    [claimId: string, condition: BigNumberish, evidenceHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allConditionsMet"
  ): TypedContractMethod<[claimId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "anchorPolicy"
  ): TypedContractMethod<
    [
      vaultId: string,
      policyId: string,
      requireExecutorIdentity: boolean,
      requireDeathCertificate: boolean,
      requireAttorneyAttestation: boolean,
      requireGuardianQuorum: boolean,
      guardianQuorumN: BigNumberish,
      guardianQuorumM: BigNumberish,
      waitingPeriodDays: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authoriseRelease"
  ): TypedContractMethod<
    [vaultId: string, claimId: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "denyClaim"
  ): TypedContractMethod<
    [claimId: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClaimState"
  ): TypedContractMethod<
    [claimId: string],
    [LegacyPolicyEngine.ReleaseStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConditions"
  ): TypedContractMethod<
    [claimId: string],
    [LegacyPolicyEngine.ConditionRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPolicy"
  ): TypedContractMethod<
    [vaultId: string],
    [LegacyPolicyEngine.ReleasePolicyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "openClaim"
  ): TypedContractMethod<
    [vaultId: string, claimId: string, claimant: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [claimId: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [claimId: string, releaseProceeds: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "satisfyCondition"
  ): TypedContractMethod<
    [claimId: string, condition: BigNumberish, evidenceHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ClaimDenied"
  ): TypedContractEvent<
    ClaimDeniedEvent.InputTuple,
    ClaimDeniedEvent.OutputTuple,
    ClaimDeniedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimOpened"
  ): TypedContractEvent<
    ClaimOpenedEvent.InputTuple,
    ClaimOpenedEvent.OutputTuple,
    ClaimOpenedEvent.OutputObject
  >;
  getEvent(
    key: "ConditionSatisfied"
  ): TypedContractEvent<
    ConditionSatisfiedEvent.InputTuple,
    ConditionSatisfiedEvent.OutputTuple,
    ConditionSatisfiedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyAnchored"
  ): TypedContractEvent<
    PolicyAnchoredEvent.InputTuple,
    PolicyAnchoredEvent.OutputTuple,
    PolicyAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "ReleaseAuthorised"
  ): TypedContractEvent<
    ReleaseAuthorisedEvent.InputTuple,
    ReleaseAuthorisedEvent.OutputTuple,
    ReleaseAuthorisedEvent.OutputObject
  >;
  getEvent(
    key: "WaitingPeriodStarted"
  ): TypedContractEvent<
    WaitingPeriodStartedEvent.InputTuple,
    WaitingPeriodStartedEvent.OutputTuple,
    WaitingPeriodStartedEvent.OutputObject
  >;

  filters: {
    "ClaimDenied(string,string,address,uint256)": TypedContractEvent<
      ClaimDeniedEvent.InputTuple,
      ClaimDeniedEvent.OutputTuple,
      ClaimDeniedEvent.OutputObject
    >;
    ClaimDenied: TypedContractEvent<
      ClaimDeniedEvent.InputTuple,
      ClaimDeniedEvent.OutputTuple,
      ClaimDeniedEvent.OutputObject
    >;

    "ClaimOpened(string,string,address,uint256)": TypedContractEvent<
      ClaimOpenedEvent.InputTuple,
      ClaimOpenedEvent.OutputTuple,
      ClaimOpenedEvent.OutputObject
    >;
    ClaimOpened: TypedContractEvent<
      ClaimOpenedEvent.InputTuple,
      ClaimOpenedEvent.OutputTuple,
      ClaimOpenedEvent.OutputObject
    >;

    "ConditionSatisfied(string,uint8,address,bytes32,uint256)": TypedContractEvent<
      ConditionSatisfiedEvent.InputTuple,
      ConditionSatisfiedEvent.OutputTuple,
      ConditionSatisfiedEvent.OutputObject
    >;
    ConditionSatisfied: TypedContractEvent<
      ConditionSatisfiedEvent.InputTuple,
      ConditionSatisfiedEvent.OutputTuple,
      ConditionSatisfiedEvent.OutputObject
    >;

    "DisputeRaised(string,string,address,uint256)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(string,bool,address,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "PolicyAnchored(string,string,uint256,uint32,uint256)": TypedContractEvent<
      PolicyAnchoredEvent.InputTuple,
      PolicyAnchoredEvent.OutputTuple,
      PolicyAnchoredEvent.OutputObject
    >;
    PolicyAnchored: TypedContractEvent<
      PolicyAnchoredEvent.InputTuple,
      PolicyAnchoredEvent.OutputTuple,
      PolicyAnchoredEvent.OutputObject
    >;

    "ReleaseAuthorised(string,string,bytes32,address,uint256)": TypedContractEvent<
      ReleaseAuthorisedEvent.InputTuple,
      ReleaseAuthorisedEvent.OutputTuple,
      ReleaseAuthorisedEvent.OutputObject
    >;
    ReleaseAuthorised: TypedContractEvent<
      ReleaseAuthorisedEvent.InputTuple,
      ReleaseAuthorisedEvent.OutputTuple,
      ReleaseAuthorisedEvent.OutputObject
    >;

    "WaitingPeriodStarted(string,uint256)": TypedContractEvent<
      WaitingPeriodStartedEvent.InputTuple,
      WaitingPeriodStartedEvent.OutputTuple,
      WaitingPeriodStartedEvent.OutputObject
    >;
    WaitingPeriodStarted: TypedContractEvent<
      WaitingPeriodStartedEvent.InputTuple,
      WaitingPeriodStartedEvent.OutputTuple,
      WaitingPeriodStartedEvent.OutputObject
    >;
  };
}
