/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LegacyVaultAnchor {
  export type ManifestAnchorStruct = {
    vaultId: string;
    manifestHash: BytesLike;
    ipfsCID: string;
    version: BigNumberish;
    anchoredBy: AddressLike;
    anchoredAt: BigNumberish;
  };

  export type ManifestAnchorStructOutput = [
    vaultId: string,
    manifestHash: string,
    ipfsCID: string,
    version: bigint,
    anchoredBy: string,
    anchoredAt: bigint
  ] & {
    vaultId: string;
    manifestHash: string;
    ipfsCID: string;
    version: bigint;
    anchoredBy: string;
    anchoredAt: bigint;
  };

  export type AttestationStruct = {
    vaultId: string;
    attester: AddressLike;
    attesterDID: string;
    role: BigNumberish;
    kind: BigNumberish;
    credentialHash: BytesLike;
    evidenceHash: BytesLike;
    timestamp: BigNumberish;
    blockHeight: BigNumberish;
  };

  export type AttestationStructOutput = [
    vaultId: string,
    attester: string,
    attesterDID: string,
    role: bigint,
    kind: bigint,
    credentialHash: string,
    evidenceHash: string,
    timestamp: bigint,
    blockHeight: bigint
  ] & {
    vaultId: string;
    attester: string;
    attesterDID: string;
    role: bigint;
    kind: bigint;
    credentialHash: string;
    evidenceHash: string;
    timestamp: bigint;
    blockHeight: bigint;
  };
}

export interface LegacyVaultAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOperator"
      | "anchorManifest"
      | "getAnchors"
      | "getAttestations"
      | "getCurrentVersion"
      | "getLatestAnchor"
      | "operators"
      | "owner"
      | "recordAttestation"
      | "removeOperator"
      | "transferOwnership"
      | "verifyManifest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AttestationRecorded" | "ManifestAnchored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorManifest",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "getAnchors", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAttestations",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentVersion",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestAnchor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordAttestation",
    values: [
      string,
      AddressLike,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyManifest",
    values: [string, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorManifest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAnchors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestAnchor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyManifest",
    data: BytesLike
  ): Result;
}

export namespace AttestationRecordedEvent {
  export type InputTuple = [
    vaultId: string,
    attester: AddressLike,
    role: BigNumberish,
    kind: BigNumberish,
    credentialHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    attester: string,
    role: bigint,
    kind: bigint,
    credentialHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    attester: string;
    role: bigint;
    kind: bigint;
    credentialHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManifestAnchoredEvent {
  export type InputTuple = [
    vaultId: string,
    manifestHash: BytesLike,
    ipfsCID: string,
    version: BigNumberish,
    anchoredBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    manifestHash: string,
    ipfsCID: string,
    version: bigint,
    anchoredBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    manifestHash: string;
    ipfsCID: string;
    version: bigint;
    anchoredBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegacyVaultAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): LegacyVaultAnchor;
  waitForDeployment(): Promise<this>;

  interface: LegacyVaultAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  anchorManifest: TypedContractMethod<
    [vaultId: string, manifestHash: BytesLike, ipfsCID: string],
    [bigint],
    "nonpayable"
  >;

  getAnchors: TypedContractMethod<
    [vaultId: string],
    [LegacyVaultAnchor.ManifestAnchorStructOutput[]],
    "view"
  >;

  getAttestations: TypedContractMethod<
    [vaultId: string],
    [LegacyVaultAnchor.AttestationStructOutput[]],
    "view"
  >;

  getCurrentVersion: TypedContractMethod<[vaultId: string], [bigint], "view">;

  getLatestAnchor: TypedContractMethod<
    [vaultId: string],
    [LegacyVaultAnchor.ManifestAnchorStructOutput],
    "view"
  >;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordAttestation: TypedContractMethod<
    [
      vaultId: string,
      attester: AddressLike,
      attesterDID: string,
      role: BigNumberish,
      kind: BigNumberish,
      credentialHash: BytesLike,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  removeOperator: TypedContractMethod<[op: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyManifest: TypedContractMethod<
    [vaultId: string, manifestHash: BytesLike, version: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "anchorManifest"
  ): TypedContractMethod<
    [vaultId: string, manifestHash: BytesLike, ipfsCID: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAnchors"
  ): TypedContractMethod<
    [vaultId: string],
    [LegacyVaultAnchor.ManifestAnchorStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAttestations"
  ): TypedContractMethod<
    [vaultId: string],
    [LegacyVaultAnchor.AttestationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentVersion"
  ): TypedContractMethod<[vaultId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestAnchor"
  ): TypedContractMethod<
    [vaultId: string],
    [LegacyVaultAnchor.ManifestAnchorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordAttestation"
  ): TypedContractMethod<
    [
      vaultId: string,
      attester: AddressLike,
      attesterDID: string,
      role: BigNumberish,
      kind: BigNumberish,
      credentialHash: BytesLike,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyManifest"
  ): TypedContractMethod<
    [vaultId: string, manifestHash: BytesLike, version: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AttestationRecorded"
  ): TypedContractEvent<
    AttestationRecordedEvent.InputTuple,
    AttestationRecordedEvent.OutputTuple,
    AttestationRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ManifestAnchored"
  ): TypedContractEvent<
    ManifestAnchoredEvent.InputTuple,
    ManifestAnchoredEvent.OutputTuple,
    ManifestAnchoredEvent.OutputObject
  >;

  filters: {
    "AttestationRecorded(string,address,uint8,uint8,bytes32,uint256)": TypedContractEvent<
      AttestationRecordedEvent.InputTuple,
      AttestationRecordedEvent.OutputTuple,
      AttestationRecordedEvent.OutputObject
    >;
    AttestationRecorded: TypedContractEvent<
      AttestationRecordedEvent.InputTuple,
      AttestationRecordedEvent.OutputTuple,
      AttestationRecordedEvent.OutputObject
    >;

    "ManifestAnchored(string,bytes32,string,uint32,address,uint256)": TypedContractEvent<
      ManifestAnchoredEvent.InputTuple,
      ManifestAnchoredEvent.OutputTuple,
      ManifestAnchoredEvent.OutputObject
    >;
    ManifestAnchored: TypedContractEvent<
      ManifestAnchoredEvent.InputTuple,
      ManifestAnchoredEvent.OutputTuple,
      ManifestAnchoredEvent.OutputObject
    >;
  };
}
